In [1]:
import sys
import torch
import numpy as np
import pandas as pd

In [ ]:
from gibbsibp import UncollapsedGibbsIBP
from util import extract_mean_from_samples, compare_distance

In [3]:
dataset = pd.read_excel('training_data.xlsx')
dataset.head()

cp_pres_1  cp_pres_2  cp_pres_3  cp_pres_4  cp_pres_5  cp_pres_6  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

   cp_pres_7  cp_pres_8  cp_pres_9  cp_pres_10  ...  cp_pres_14  cp_pres_15  \
0          0          0          0           0  ...           0           0   
1          0          0          0           0  ...           0           0   
2          0          0          0           0  ...           0           0   
3          0          0          0           0  ...           0           0   
4          0          0          0           0  ...           0           0   

   cp_pres_16  cp_pres_17  cp_pres_18  cp_pres_19  cp_pres_20  cp_pres_21  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   cp_pres_22  cp_pres_23  
0           0           0  
1           0           0  
2           0           0  
3           0           0  
4           0           0  

[5 rows x 23 columns]

In [ ]:

"""
 1): base element
    /-----\
    | \   |
    |  o  X
    |     |
    \-----/

 2): base element
    /-----\
    |   / |
    X  o  |
    |     |
    \-----/

3): not visual and not dynamic compositional
    /--X--\
    |     |
    |  o  |
    |  |  |
    \-----/

4): not visual but dynamic compositional
    /-----\
    |     |
    |  o  |
    |   \ |
    \--X--/

5): visual and dynamic compositional
    /-----\
    |  |  |
    X  o  X
    |     |
    \-----/

6): not dynamic but visual compositional
    /--X--\
    |     |
    X  o  |
    | /   |
    \-----/
"""

conditions = []
conditions.append({'force':np.array([ 0., 0.]),             'cue':np.array([0., 0., 0., 0.,])}) # 0: is null/ control you can ignore
conditions.append({'force':np.array([-0.866025404, 0.5]),   'cue':np.array([1., 0., 0., 0.,])}) # 1,2: elements
conditions.append({'force':np.array([ 0.866025404, 0.5]),   'cue':np.array([0., 0., 1., 0.,])})
conditions.append({'force':np.array([ 0.,-1.]),             'cue':np.array([0., 1., 0., 0.,])}) # 3: not visual and not dynamic compositional
conditions.append({'force':np.array([ 0.866025404, -0.5]),  'cue':np.array([0., 0., 0., 1.,])}) # 4: not visual but dynamic compositional
conditions.append({'force':np.array([ 0, 1]),               'cue':np.array([1., 0., 1., 0.,])}) # 5: visual and dynamic compositional
conditions.append({'force':np.array([-0.866025404, -0.5]),  'cue':np.array([0., 1., 1., 0.,])}) # 6: not dynamic but visual compositional

# temporary division by 4, to make the model converge
for condition in conditions:
    condition['force'] = condition['force']/4

true_A = []
true_Y = []
for i, condition in enumerate(conditions):
    if i > 0:
        true_A.append(condition['force'])
        true_Y.append(condition['cue'])

In [5]:
def generate_input_data(condition_seq):
    """
    Generate input data for the model, based on sequences of conditions experienced by the subjects.
    """
    X_dataset = []
    F_dataset = []

    for condition in condition_seq:
        X_dataset.append(conditions[condition]['cue'])
        F_dataset.append(conditions[condition]['force'])

    X_dataset = torch.tensor(X_dataset, dtype=torch.float32)
    F_dataset = torch.tensor(F_dataset, dtype=torch.float32)

    return X_dataset, F_dataset

In [ ]:
seq_1 = dataset['cp_pres_1'].to_list()
seq_1 = [int(x) for x in seq_1]
seq_1 = [x for x in seq_1 if x != 0]
print(len(seq_1))

X_dataset, F_dataset = generate_input_data(seq_1)

630


In [7]:
# def add_noise_to_obs(X, F, F_noise_std = 0.01, lambd=0.98, epsilon=0.02):
#     """
#     Add gaussian noise to force data, and randomly flip pixels in the observation data
#     """
#     F += torch.randn(F.size()) * F_noise_std
    
#     X_noisy = torch.zeros(X.size())
#     for i in range(X.size()[0]):
#         for j in range(X.size()[1]):
#             if X[i, j] == 1:
#                 X_noisy[i, j] = 1 if random() < lambd else 0
#             else:
#                 X_noisy[i, j] = 1 if random() < epsilon else 0

#     return X_noisy, F

In [8]:
# X_dataset, F_dataset = add_noise_to_obs(X_dataset, F_dataset)

print(X_dataset[:5,])
print(F_dataset[:5,])

tensor([[0., 1., 1., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.]])
tensor([[-0.2165, -0.1250],
        [-0.2165,  0.1250],
        [ 0.2165, -0.1250],
        [ 0.2165,  0.1250],
        [ 0.0000, -0.2500]])


In [1]:
# Import cProfile
# inf = UncollapsedGibbsIBP(alpha=0.05, K=1, max_K=4, sigma_a=0.2, sigma_n=0.1, epsilon=0.05, lambd=0.99, phi=0.25)
# with cProfile.Profile() as pr:
#     As, Zs, Ys = inf.gibbs(F_dataset, X_dataset, 5)

# pr.print_stats(sort='cumtime')

In [19]:
inf = UncollapsedGibbsIBP(alpha=0.05, K=1, max_K=6, sigma_a=0.2, sigma_n=0.05, epsilon=0.01, lambd=0.99, phi=0.25)

As, Zs, Ys = inf.gibbs(F_dataset, X_dataset, 100)

In [27]:
A, Z, Y = extract_mean_from_samples(As, Zs, Ys, n=95)
print(A*4)
print(Y)
print(Z)

[[ 0.88 -0.48]
 [ 0.88  0.52]
 [-0.88 -0.52]
 [ 0.   -1.  ]
 [-0.88  0.52]]
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]


In [ ]:
A, Z, Y = extract_mean_from_samples(As, Zs, Ys, n=10)

reorder = compare_distance(true_A.numpy(), A)

print("True A:")
print(true_A.numpy())
print("Inferred A:")
print(np.round(reorder @ A,2))

print("\nTrue Y:")
print(true_Y.numpy())
print("Inferred Y:")
print(np.round(reorder @ Y,2))

print("\nTrue Z:")
print(np.array(Z_latent))
print("Inferred Z:")
print(np.round(Z @ reorder,0))

True A:
[[ 0.2  0.2]
 [-0.2  0.2]
 [ 0.  -0.2]]
Inferred A:
[[ 0.21  0.19]
 [-0.2   0.18]
 [-0.01 -0.17]]

True Y:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
Inferred Y:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]

True Z:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]
 [1 1 1]]
Inferred Z:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 1.]
 [1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 1.]]
